### ISSUE TITLE
setting signal or store triggers UI-update of previous value

### ISSUE THREAD

**Issue by vincentvandijck** [solidjs/react-solid-state#2]
setting a signal or setting a store does trigger an update of the UI, but its previous value is being rendered instead of the updated value.

example with Signal: https://codesandbox.io/s/determined-satoshi-v2xk8?file=/src/App.js
example with Store: https://codesandbox.io/s/frosty-silence-syubp?file=/src/App.js

**Comment by vincentvandijck** [comment]
upon further investigation i notice that switching the order of setStore and setSignal flips the behavior.
basically any arbitrary state change, after the setting of the signal/store, creates the behavior: 
p.ex https://codesandbox.io/s/determined-satoshi-v2xk8?file=/src/App.js

**Comment by ryansolid** [comment]
Thanks for the reproductions, React can be a bit to juggle this way and I wonder if I should be looking to update the approach again. In any case I will take a look when I get a chance.

**Comment by ryansolid** [comment]
Ok try version 0.27.1. The problem was in how nested updates were queued. I forced this on a microtask which was the easiest fix but not sure if there are other reprocussions.

**Comment by vincentvandijck** [comment]
lovely. seems to be working great in the minimal examples. thank you!
I'll implement it in my react native app and will let u know if I face any issues there.

in the meanwhile I wrote a wrapper around react's createState to mimick how Solid's useStore works:
https://codesandbox.io/s/wonderful-lamport-lb7c5
